# Generated by Django 4.2.4 on 2023-10-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlog',
            name='date_time_consumed',
            field=models.DateTimeField(),
        ),
    ]
