# Generated by Django 4.2.4 on 2023-10-30 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('average_calories', models.FloatField()),
                ('highest_calories_day', models.DateField()),
                ('lowest_calories_day', models.DateField()),
                ('average_proteins', models.FloatField()),
                ('average_carbs', models.FloatField()),
                ('average_fats', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='GoalAchievementReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('goal_type', models.CharField(choices=[('CALORIE', 'Calorie Intake'), ('PROTEIN', 'Protein Intake'), ('CARB', 'Carb Intake'), ('FAT', 'Fat Intake')], max_length=50)),
                ('goal_value', models.FloatField()),
                ('achieved_value', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'month', 'year', 'goal_type')},
            },
        ),
        migrations.CreateModel(
            name='ComparisonReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_month', models.PositiveIntegerField()),
                ('start_year', models.PositiveIntegerField()),
                ('end_month', models.PositiveIntegerField()),
                ('end_year', models.PositiveIntegerField()),
                ('change_in_calories', models.FloatField()),
                ('change_in_proteins', models.FloatField()),
                ('change_in_carbs', models.FloatField()),
                ('change_in_fats', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'start_month', 'start_year', 'end_month', 'end_year')},
            },
        ),
    ]
