# Generated by Django 4.2.4 on 2023-10-30 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highest_calories_in_a_day', models.PositiveIntegerField(default=0)),
                ('lowest_calories_in_a_day', models.PositiveIntegerField(default=0)),
                ('average_daily_calories', models.FloatField(default=0)),
                ('total_days_tracked', models.PositiveIntegerField(default=0)),
                ('average_daily_protein', models.FloatField(default=0)),
                ('average_daily_carbs', models.FloatField(default=0)),
                ('average_daily_fat', models.FloatField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dietary_preference', models.CharField(choices=[('VEG', 'Vegetarian'), ('NON_VEG', 'Non-Vegetarian'), ('VEGAN', 'Vegan')], default='VEG', max_length=100)),
                ('send_email_notifications', models.BooleanField(default=True)),
                ('theme_preference', models.CharField(choices=[('LIGHT', 'Light Mode'), ('DARK', 'Dark Mode')], default='LIGHT', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('bio', models.TextField(blank=True)),
                ('target_daily_calories', models.PositiveIntegerField(default=2400)),
                ('total_calories_consumed', models.PositiveIntegerField(default=0)),
                ('total_proteins_consumed', models.PositiveIntegerField(default=0)),
                ('total_carbs_consumed', models.PositiveIntegerField(default=0)),
                ('total_fats_consumed', models.PositiveIntegerField(default=0)),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('target_protein', models.FloatField(default=360)),
                ('target_carbs', models.FloatField(default=75)),
                ('target_fat', models.FloatField(default=66)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_calories', models.PositiveIntegerField(default=0)),
                ('total_protein', models.FloatField(default=0)),
                ('total_carbs', models.FloatField(default=0)),
                ('total_fat', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
