# Generated by Django 4.2.4 on 2023-10-30 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='total_carbs_consumed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_fats_consumed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_proteins_consumed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='target_carbs',
            field=models.FloatField(default=75),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='target_daily_calories',
            field=models.PositiveIntegerField(default=2400),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='target_fat',
            field=models.FloatField(default=66),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='target_protein',
            field=models.FloatField(default=360),
        ),
    ]
